#define MAINPREFIX z
#define PREFIX tfp

#include "script_version.hpp"

#define VERSION     MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR  MAJOR,MINOR,PATCHLVL,BUILD

#define REQUIRED_VERSION 2.14
#define REQUIRED_CBA_VERSION {3,16,0}

#ifdef SUBCOMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(Task Force Prometheus Factions - COMPONENT_BEAUTIFIED - SUBCOMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(Task Force Prometheus Factions - COMPONENT_BEAUTIFIED)
#endif
